### ISSUE TITLE
Geometry.close(...) call with keyword "idx=" specified

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#12]
**Revision** SISL **e1ec907**

**This code fails to run:**
>from __future__ import print_function, division
import sisl
import numpy as N
xyz = [[i,0,0] for i in range(10)]
geom = sisl.Geometry(xyz)
dR = (0.1,1.1)
for ia in geom:
   idx = geom.close(ia, dR=dR)
for ia in geom:
   idx = geom.close(ia, dR=dR, idx=range(5))

First loop is OK, the second one fails

**Error message:**
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    idx = geom.close(ia, dR=dR, idx=range(5))
  File "/scratch/thf/SOFTWARE/python/2.7.10/gcc-4.9.2/packages/sisl/e1ec907/gcc-4.9.2/lib/python2.7/site-packages/sisl/geometry.py", line 1266, in close
    ret_dist=ret_dist)
  File "/scratch/thf/SOFTWARE/python/2.7.10/gcc-4.9.2/packages/sisl/e1ec907/gcc-4.9.2/lib/python2.7/site-packages/sisl/geometry.py", line 1051, in close_sc
    idx = idx[ix]
TypeError: only integer arrays with one element can be converted to an index

**Any clue?**

**Comment by zerothi** [comment]
Thanks for the bug-report!
