### ISSUE TITLE
SileGULP cannot read geometry

### ISSUE THREAD

**Issue by ratatoskr129** [zerothi/sisl#318]
Hi,

I am a new SISL user. I want to calculate phonon transmission function using PHtrans for layered heterostructures. Therefore, I need to calculate the phonon dynamical matrix using GULP first.

To get familiar with the calculations, I was trying to calculate the phonon dynamical matrix of a structure that has 12 layers of MoSe2. I am using the following input file:
```python
import sisl

with open('zz.gin', 'w') as f:
f.write("""single conv dist full nosymmetry phon dynamical_matrix nod3
output she
cutd 3.0

cell
3.3269493580 3.3269493580 92.7085342407 90 90 120

cartesian 36
Mo core 0.000000000 1.920815229 3.862855673 0 1 0 0 0 0
Mo core 0.000000000 1.920815229 19.314279556 0 1 0 0 0 0
Mo core 0.000000000 1.920815229 34.765701294 0 1 0 0 0 0
Mo core 0.000000000 1.920815229 50.217124939 0 1 0 0 0 0
Mo core 0.000000000 1.920815229 65.668548584 0 1 0 0 0 0
Mo core 0.000000000 1.920815229 81.119964600 0 1 0 0 0 0
Mo core 1.663474798 0.960407615 11.588566780 0 1 0 0 0 0
Mo core 1.663474798 0.960407615 27.039991379 0 1 0 0 0 0
Mo core 1.663474798 0.960407615 42.491413116 0 1 0 0 0 0
Mo core 1.663474798 0.960407615 57.942832947 0 1 0 0 0 0
Mo core 1.663474798 0.960407615 73.394256592 0 1 0 0 0 0
Mo core 1.663474798 0.960407615 88.845680237 0 1 0 0 0 0
Se core 1.663474798 0.960407615 5.535471916 0 1 0 0 0 0
Se core 1.663474798 0.960407615 20.986894608 0 1 0 0 0 0
Se core 1.663474798 0.960407615 36.438316345 0 1 0 0 0 0
Se core 1.663474798 0.960407615 51.889739990 0 1 0 0 0 0
Se core 1.663474798 0.960407615 67.341163635 0 1 0 0 0 0
Se core 1.663474798 0.960407615 82.792587280 0 1 0 0 0 0
Se core 0.000000000 1.920815229 13.261183739 0 1 0 0 0 0
Se core 0.000000000 1.920815229 28.712608337 0 1 0 0 0 0
Se core 0.000000000 1.920815229 44.164028168 0 1 0 0 0 0
Se core 0.000000000 1.920815229 59.615451813 0 1 0 0 0 0
Se core 0.000000000 1.920815229 75.066871643 0 1 0 0 0 0
Se core 0.000000000 1.920815229 90.518295288 0 1 0 0 0 0
Se core 1.663474798 0.960407615 2.190238953 0 1 0 0 0 0
Se core 1.663474798 0.960407615 17.641662598 0 1 0 0 0 0
Se core 1.663474798 0.960407615 33.093082428 0 1 0 0 0 0
Se core 1.663474798 0.960407615 48.544506073 0 1 0 0 0 0
Se core 1.663474798 0.960407615 63.995933533 0 1 0 0 0 0
Se core 1.663474798 0.960407615 79.447349548 0 1 0 0 0 0
Se core 0.000000000 1.920815229 9.915949821 0 1 0 0 0 0
Se core 0.000000000 1.920815229 25.367374420 0 1 0 0 0 0
Se core 0.000000000 1.920815229 40.818794250 0 1 0 0 0 0
Se core 0.000000000 1.920815229 56.270217896 0 1 0 0 0 0
Se core 0.000000000 1.920815229 71.721641541 0 1 0 0 0 0
Se core 0.000000000 1.920815229 87.173057556 0 1 0 0 0 0

sw2
Mo Se 5.737 0.913 18.787 0.0 3.351
sw3
Mo Se Se 32.526 82.119 0.913 3.351 3.351 4.000
lennard epsilon
Se Mo 3.6285 0.0055400 0.0 12.0
lennard epsilon
Se Se 4.205 0.0126000 0.0 12.0
lennard epsilon
Mo Mo 3.052 0.0024300 0.0 12.0
""")

Create PHtrans input
with open('ZZ.fdf', 'w') as f:
f.write("""SystemLabel ZZ

TBT.DOS.Gf T

TBT.k [51 51 1]

TBT.HS DEVICE_zz.nc

%block TBT.Contour.line
part line
from 0. eV to .25 eV
points 400
method mid-rule
%endblock TBT.Contour.line

%block TBT.Elec.Left
HS ELEC_zz.nc
semi-inf-direction -a3
electrode-position 1
%endblock
%block TBT.Elec.Right
HS ELEC_zz.nc
semi-inf-direction +a3
electrode-position end -1
%endblock
""")

import os
if not os.path.exists('zz.gout'):
raise ValueError("zz.gin has not been runned by GULP")

print('Reading output')
gout = sisl.get_sile('zz.gout')

#gout.set_dynamical_matrix_key('Real Dynamical matrix')
gout.set_supercell_key("Cartesian lattice vectors")
geo=gout.read_geometry()
print('geo')
```

## Error

But when it tries to read the geometry from the `zz.gout` file, the following errors occurs:
```shell
Traceback (most recent call last):
File "input.py", line 109, in
geo=gout.read_geometry()
File "/home/my/.local/lib/python3.6/site-packages/sisl/io/sile.py", line 519, in pre_open
return func(self, *args, **kwargs)
File "/home/my/.local/lib/python3.6/site-packages/sisl/io/gulp/got.py", line 154, in read_geometry
'This could not be found found in file: "{}".'.format(self.file))
ValueError: SileGULP tries to lookup the SuperCell or Geometry.
None succeeded, ensure file has correct format.
This could not be found found in file: "zz.gout".
```
Would you please help me to find the error in the input file? I would greatly appreciate your help.

Thank you.

Edit: Issue resolved.

**Comment by zerothi** [comment]
How did you resolve it? It may be useful for other users, I would like to revert your issue so it remains if that is fine?

**Comment by ratatoskr129** [comment]
Hi Nick,

I am really sorry, I missed your response. Please revert the issue if needed.

If you look at the GULP options, I was using 'single' (see below). And that was the problem. 

f.write("""single conv dist full nosymmetry phon dynamical_matrix nod3

When I replaced it with 'opti' it worked fine.

f.write("""opti conv dist full nosymmetry phon dynamical_matrix nod3

**Comment by zerothi** [comment]
Great, thanks for clearing this out. I'll close it now since you brought the answer! :)
