### ISSUE TITLE
`Geometry ` coordinates as f-contiguous array

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#748]
Passing an f-contiguous coordinate array to `Geometry` exposes an issue in sisl, exposed by this minimal example
```python
import sisl
import numpy as np

x = np.arange(10)
xyz = np.array([x, x, x]).T
print(xyz.flags)
geom = sisl.Geometry(xyz)
```
resulting in
```python
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Traceback (most recent call last):
  File "/home/me/test.py", line 7, in <module>
    geom = sisl.Geometry(xyz)
  File "/home/me/.local/lib/python3.10/site-packages/sisl/messages.py", line 106, in wrapped
    return func(*args, **kwargs)
  File "/home/me/.local/lib/python3.10/site-packages/sisl/_core/geometry.py", line 194, in __init__
    self._init_lattice(lattice)
  File "/home/me/.local/lib/python3.10/site-packages/sisl/_core/geometry.py", line 212, in _init_lattice
    closest = self.close(0, R=(0.0, 0.4, 5.0))[2]
  File "/home/me/.local/lib/python3.10/site-packages/sisl/_core/geometry.py", line 2754, in close
    sret = self.close_sc(
  File "/home/me/.local/lib/python3.10/site-packages/sisl/_core/geometry.py", line 2376, in close_sc
    atoms, d = indices_in_sphere_with_dist(dxa, max_R)
  File "_indices.pyx", line 286, in sisl._indices.indices_in_sphere_with_dist
ValueError: ndarray is not C-contiguous
```

**Version details**
```python
>>> import sys
>>> print(sys.version)
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
>>> import sisl
>>> print(sisl.__version__)
0.14.4.dev339+g56bb42843
>>> import numpy as np
>>> print(np.__version__)
1.24.0
```

**Comment by zerothi** [comment]
This might also be present for the lattice parameters, come to think of it...

**Comment by zerothi** [comment]
Also fixed for `Lattice`

**Comment by tfrederiksen** [comment]
> This might also be present for the lattice parameters, come to think of it...

I thought about it too, but couldn't produce a problematic example.

**Comment by zerothi** [comment]
It should have been fixed now, the problem, I think, would occur when calculating the reciprocal lattice. In any case we won't see it now ;)
Thanks!
