### ISSUE TITLE
issue while installing Sisl 0.94 version

### ISSUE THREAD

**Issue by alokrs18** [zerothi/sisl#81]
**Describe the issue**
after installing the programme, on running the the executable sdat or sgeom , the follwing erros comes.

sgeom siesta_input.fdf siesta_input.xyz 
Traceback (most recent call last):
  File "/usr/bin/sgeom", line 9, in <module>
    load_entry_point('sisl==0.9.1', 'console_scripts', 'sgeom')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/sisl-0.9.1-py2.7-linux-x86_64.egg/sisl/__init__.py", line 72, in <module>
    from .supercell import *
  File "/usr/lib64/python2.7/site-packages/sisl-0.9.1-py2.7-linux-x86_64.egg/sisl/supercell.py", line 12, in <module>
    import sisl.linalg as lin
  File "/usr/lib64/python2.7/site-packages/sisl-0.9.1-py2.7-linux-x86_64.egg/sisl/linalg/__init__.py", line 40, in <module>
    from .base import *
  File "/usr/lib64/python2.7/site-packages/sisl-0.9.1-py2.7-linux-x86_64.egg/sisl/linalg/base.py", line 6, in <module>
    from scipy.linalg.lapack import get_lapack_funcs, _compute_lwork
ImportError: cannot import name _compute_lwork

**Version details  sisl 0.9.4**
Run the below code and add to issue (if an issue is relevant for the issue):
```python
import sys
print(sys.version)
2.7.13 (default, May 10 2017, 20:04:36) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

import sisl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/__init__.py", line 58, in <module>
    from . import info
ImportError: cannot import name info


print(sisl.__version__)
print(sisl.__git_revision__)
```

**Comment by zerothi** [comment]
It seems to me that you have two different versions installed?

I.e. the first error messages specify sisl 0.9.1, while the latter specifies, 0.9.4.

Having two different versions may complicate load paths. Could you try and purge all sisl installations and re-install sisl?

**Comment by alokrs18** [comment]
I uninstalled the previous version and installed sisl 0.9.4 through 'pip install sisl[analysis].

[root@localhost codes]# pip install sisl[analysis]
Collecting sisl[analysis]
  Using cached https://files.pythonhosted.org/packages/54/d5/cff8b85f3471753cf2fd7f9530707f1fca26263c2f1351b50f9ccd4442d4/sisl-0.9.4.tar.gz
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from sisl[analysis]) (20.1.1)
Requirement already satisfied: numpy>=1.10 in /usr/lib64/python2.7/site-packages (from sisl[analysis]) (1.15.1)
Requirement already satisfied: xarray>=0.10.0 in /usr/lib/python2.7/site-packages (from sisl[analysis]) (0.10.8)
Requirement already satisfied: tqdm in /usr/lib/python2.7/site-packages (from sisl[analysis]) (4.26.0)
Requirement already satisfied: pandas>=0.19.2 in /usr/lib64/python2.7/site-packages (from xarray>=0.10.0->sisl[analysis]) (0.23.4)
Requirement already satisfied: pytz>=2011k in /usr/lib/python2.7/site-packages (from pandas>=0.19.2->xarray>=0.10.0->sisl[analysis]) (2016.6.1)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/lib/python2.7/site-packages (from pandas>=0.19.2->xarray>=0.10.0->sisl[analysis]) (2.6.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil>=2.5.0->pandas>=0.19.2->xarray>=0.10.0->sisl[analysis]) (1.10.0)
Installing collected packages: sisl
  Running setup.py install for sisl ... done
Successfully installed sisl-0.9.4


after this when i try to execute sgeom or sdata , the follwing errors are coming up


[alok@localhost codes]$ sgeom --help
Traceback (most recent call last):
  File "/usr/bin/sgeom", line 9, in <module>
    load_entry_point('sisl==0.9.4', 'console_scripts', 'sgeom')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/__init__.py", line 90, in <module>
    from . import linalg
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/linalg/__init__.py", line 30, in <module>
    from .base import *
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/linalg/base.py", line 6, in <module>
    from scipy.linalg.lapack import get_lapack_funcs, _compute_lwork
ImportError: cannot import name _compute_lwork


import sisl

>>> import sisl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/__init__.py", line 90, in <module>
    from . import linalg
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/linalg/__init__.py", line 30, in <module>
    from .base import *
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/linalg/base.py", line 6, in <module>
    from scipy.linalg.lapack import get_lapack_funcs, _compute_lwork
ImportError: cannot import name _compute_lwork


looking forward for help

**Comment by zerothi** [comment]
I believe I have left out a dependency.

Could you do:

```bash
pip install scipy netCDF4
```
and retry `import sisl`?

**Comment by alokrs18** [comment]
[root@localhost codes]# pip install scipy netCDF4
Requirement already satisfied: scipy in /usr/lib64/python2.7/site-packages (0.16.1)
Requirement already satisfied: netCDF4 in /usr/lib64/python2.7/site-packages (1.2.2)
Requirement already satisfied: numpy>=1.7 in /usr/lib64/python2.7/site-packages (from netCDF4) (1.15.1)

[alok@localhost codes]$ python
Python 2.7.13 (default, May 10 2017, 20:04:36) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sisl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/__init__.py", line 90, in <module>
    from . import linalg
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/linalg/__init__.py", line 30, in <module>
    from .base import *
  File "/home/alok/.local/lib/python2.7/site-packages/sisl-0.9.4-py2.7-linux-x86_64.egg/sisl/linalg/base.py", line 6, in <module>
    from scipy.linalg.lapack import get_lapack_funcs, _compute_lwork
ImportError: cannot import name _compute_lwork

**Comment by zerothi** [comment]
You need a `scipy` version larger than 0.18, try:

```bash
pip install scipy>=0.18
```

**Comment by alokrs18** [comment]
thanks, I installed  scipy-1.1.0, which solved the problem
